@url=http://localhost:8888/v1/api
# signup
POST {{url}}/shop/signup
Content-Type: application/json

{
    "name" : "at112Shop",
    "email": "at112@gmail.com",
    "password":"abc123"
}

###
GET http://localhost:8888/ 
