version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: tip-pro-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "127.0.0.1:${MONGO_PORT}:27017"
    volumes:
      - type: bind
        source: ./mongodb/data
        target: /data/db
      - type: bind
        source: ./mongodb/mongod.conf
        target: /etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
  redis-order-distributed-key:
    image: redis
    container_name: redis-order-distributed-key
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - type: bind
        source: ./redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
      - type: bind
        source: ./redis/data
        target: /data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
